config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  resources :slides, only: [ :show ]

  root "slides#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :slide
end

app/models/slide.rb
class Slide < ApplicationRecord
  has_many :parts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  def index
    redirect_to Slide.first
  end

  def show
    @slide = Slide.find(params[:id])

    @slide_next = Slide.where("id > ?", @slide.id).order(id: :asc).first
    @slide_prev = Slide.where("id < ?", @slide.id).order(id: :desc).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Presentation On Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style><%= Rouge::Themes::Github.mode(:dark).render(scope: '.highlight') %></style>
  </head>

  <body>
    <main class="w-screen h-screen">
      <%= yield %>
    </main>
  </body>
</html>

app/views/parts/_container.html.erb
<div class="w-full mt-12 text-4xl leading-relaxed">
  <%= contents.html_safe %>
</div>

app/views/parts/_headline.html.erb
<div class="w-full h-full text-8xl font-semibold text-center flex justify-center items-center leading-normal">
  <%= contents.html_safe %>
</div>

app/views/parts/_image.html.erb
<div class="w-full h-full flex justify-center items-center">
  <img src="<%= contents.html_safe %>" class="h-3/4" />
</div>

app/views/parts/_list.html.erb
<div class="w-full mt-12 text-4xl leading-loose">
  <ul class="list-disc pl-8">
    <%= contents.html_safe %>
  </ul>
</div>

app/views/parts/_part.html.erb
<%= render partial: "/parts/#{part.part_type}", locals: { contents: part.contents } %>

app/views/parts/_partial.html.erb
<%= render partial: contents %>

app/views/parts/code/_html.html.erb
<div class="bg-black text-green-300 text-3xl leading-10 font-mono p-4 mt-8 rounded-md overflow-x-auto highlight">
  <pre><%=
    Rouge::Formatters::HTML.new.format(
      Rouge::Lexers::HTML.new.lex(contents.strip)
    ).html_safe %></pre>
</div>

app/views/parts/code/_javascript.html.erb
<div class="bg-black text-green-300 text-3xl leading-10 font-mono p-4 mt-8 rounded-md overflow-x-auto highlight">
  <pre><%=
    Rouge::Formatters::HTML.new.format(
      Rouge::Lexers::Javascript.new.lex(contents.strip)
    ).html_safe %></pre>
</div>

app/views/parts/code/_ruby.html.erb
<div class="bg-black text-green-300 text-3xl leading-10 font-mono p-4 mt-8 rounded-md overflow-x-auto highlight">
  <pre><%=
    Rouge::Formatters::HTML.new.format(
      Rouge::Lexers::Ruby.new.lex(contents.strip)
    ).html_safe %></pre>
</div>

app/views/slides/_header.html.erb
<div class="w-full h-auto text-xl md:text-8xl font-semibold"><%= contents.html_safe %></div>

app/views/slides/_slide.html.erb
<% if slide.title.present? %>
  <%= render partial: 'header', locals: { contents: slide.title } %>
<% end %>

<%= render slide.parts.order(:position) %>

app/views/slides/seeds/_example.erb
<div class="w-full flex justify-center gap-4 text-8xl mt-24">
  <div class="w-1/2">
    Hi
  </div>
  <div class="w-1/2">
    There
  </div>
</div>

app/views/slides/show.html.erb
<div class="w-full h-full font-normal overflow-hidden bg-black">
  <turbo-frame id="slide">
    <div class="slide bg-red-100 absolute top-0 right-0 left-0 bottom-0 p-6 md:px-24 md:py-14">
      <%= render @slide %>
    </div>
  </turbo-frame>

  <div class="hidden">
    <% if @slide_prev %>
      <a href="<%= slide_path(@slide_prev) %>"
         data-controller="slides"
         data-action="keydown.n@window->slides#click keydown.page_up@window->slides#click">
        <<
      </a>
    <% end %>

    <% if @slide_next %>
      <a href="<%= slide_path(@slide_next) %>"
         data-controller="slides"
         data-action="keydown.m@window->slides#click keydown.page_down@window->slides#click">
        >>
      </a>
    <% end %>
  </div>
</div>